from . import models
from . import res_partner
from . import rental_zipcode
from . import product_category
from . import rental_section
from . import sale_order
from . import sale_order_line
from . import account_move_line
from . import product_template